version: '3.8'
services:
  postgresDB:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notes_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5436:5432'
